/**
 * Complete list of countries with Dutch and English names
 * Sorted alphabetically by Dutch name
 */
export const COUNTRIES = [
    { nl: 'Afghanistan', en: 'Afghanistan', code: 'AF' },
    { nl: 'Albanië', en: 'Albania', code: 'AL' },
    { nl: 'Algerije', en: 'Algeria', code: 'DZ' },
    { nl: 'Andorra', en: 'Andorra', code: 'AD' },
    { nl: 'Angola', en: 'Angola', code: 'AO' },
    { nl: 'Argentinië', en: 'Argentina', code: 'AR' },
    { nl: 'Armenië', en: 'Armenia', code: 'AM' },
    { nl: 'Australië', en: 'Australia', code: 'AU' },
    { nl: 'Azerbeidzjan', en: 'Azerbaijan', code: 'AZ' },
    { nl: 'Bahama\'s', en: 'Bahamas', code: 'BS' },
    { nl: 'Bahrein', en: 'Bahrain', code: 'BH' },
    { nl: 'Bangladesh', en: 'Bangladesh', code: 'BD' },
    { nl: 'België', en: 'Belgium', code: 'BE' },
    { nl: 'Belize', en: 'Belize', code: 'BZ' },
    { nl: 'Benin', en: 'Benin', code: 'BJ' },
    { nl: 'Bhutan', en: 'Bhutan', code: 'BT' },
    { nl: 'Bolivia', en: 'Bolivia', code: 'BO' },
    { nl: 'Bosnië en Herzegovina', en: 'Bosnia and Herzegovina', code: 'BA' },
    { nl: 'Botswana', en: 'Botswana', code: 'BW' },
    { nl: 'Brazilië', en: 'Brazil', code: 'BR' },
    { nl: 'Brunei', en: 'Brunei', code: 'BN' },
    { nl: 'Bulgarije', en: 'Bulgaria', code: 'BG' },
    { nl: 'Cambodja', en: 'Cambodia', code: 'KH' },
    { nl: 'Canada', en: 'Canada', code: 'CA' },
    { nl: 'Chili', en: 'Chile', code: 'CL' },
    { nl: 'China', en: 'China', code: 'CN' },
    { nl: 'Colombia', en: 'Colombia', code: 'CO' },
    { nl: 'Congo', en: 'Congo', code: 'CG' },
    { nl: 'Costa Rica', en: 'Costa Rica', code: 'CR' },
    { nl: 'Kroatië', en: 'Croatia', code: 'HR' },
    { nl: 'Cuba', en: 'Cuba', code: 'CU' },
    { nl: 'Cyprus', en: 'Cyprus', code: 'CY' },
    { nl: 'Tsjechië', en: 'Czech Republic', code: 'CZ' },
    { nl: 'Denemarken', en: 'Denmark', code: 'DK' },
    { nl: 'Dominicaanse Republiek', en: 'Dominican Republic', code: 'DO' },
    { nl: 'Dubai', en: 'Dubai', code: 'AE' },
    { nl: 'Duitsland', en: 'Germany', code: 'DE' },
    { nl: 'Ecuador', en: 'Ecuador', code: 'EC' },
    { nl: 'Egypte', en: 'Egypt', code: 'EG' },
    { nl: 'El Salvador', en: 'El Salvador', code: 'SV' },
    { nl: 'Estland', en: 'Estonia', code: 'EE' },
    { nl: 'Ethiopië', en: 'Ethiopia', code: 'ET' },
    { nl: 'Fiji', en: 'Fiji', code: 'FJ' },
    { nl: 'Filipijnen', en: 'Philippines', code: 'PH' },
    { nl: 'Finland', en: 'Finland', code: 'FI' },
    { nl: 'Frankrijk', en: 'France', code: 'FR' },
    { nl: 'Georgië', en: 'Georgia', code: 'GE' },
    { nl: 'Ghana', en: 'Ghana', code: 'GH' },
    { nl: 'Griekenland', en: 'Greece', code: 'GR' },
    { nl: 'Guatemala', en: 'Guatemala', code: 'GT' },
    { nl: 'Haïti', en: 'Haiti', code: 'HT' },
    { nl: 'Honduras', en: 'Honduras', code: 'HN' },
    { nl: 'Hongarije', en: 'Hungary', code: 'HU' },
    { nl: 'Hongkong', en: 'Hong Kong', code: 'HK' },
    { nl: 'Ierland', en: 'Ireland', code: 'IE' },
    { nl: 'IJsland', en: 'Iceland', code: 'IS' },
    { nl: 'India', en: 'India', code: 'IN' },
    { nl: 'Indonesië', en: 'Indonesia', code: 'ID' },
    { nl: 'Irak', en: 'Iraq', code: 'IQ' },
    { nl: 'Iran', en: 'Iran', code: 'IR' },
    { nl: 'Israël', en: 'Israel', code: 'IL' },
    { nl: 'Italië', en: 'Italy', code: 'IT' },
    { nl: 'Ivoorkust', en: 'Ivory Coast', code: 'CI' },
    { nl: 'Jamaica', en: 'Jamaica', code: 'JM' },
    { nl: 'Japan', en: 'Japan', code: 'JP' },
    { nl: 'Jordanië', en: 'Jordan', code: 'JO' },
    { nl: 'Kazachstan', en: 'Kazakhstan', code: 'KZ' },
    { nl: 'Kenia', en: 'Kenya', code: 'KE' },
    { nl: 'Koeweit', en: 'Kuwait', code: 'KW' },
    { nl: 'Letland', en: 'Latvia', code: 'LV' },
    { nl: 'Libanon', en: 'Lebanon', code: 'LB' },
    { nl: 'Libië', en: 'Libya', code: 'LY' },
    { nl: 'Liechtenstein', en: 'Liechtenstein', code: 'LI' },
    { nl: 'Litouwen', en: 'Lithuania', code: 'LT' },
    { nl: 'Luxemburg', en: 'Luxembourg', code: 'LU' },
    { nl: 'Macao', en: 'Macau', code: 'MO' },
    { nl: 'Madagaskar', en: 'Madagascar', code: 'MG' },
    { nl: 'Maleisië', en: 'Malaysia', code: 'MY' },
    { nl: 'Malediven', en: 'Maldives', code: 'MV' },
    { nl: 'Malta', en: 'Malta', code: 'MT' },
    { nl: 'Marokko', en: 'Morocco', code: 'MA' },
    { nl: 'Mauritius', en: 'Mauritius', code: 'MU' },
    { nl: 'Mexico', en: 'Mexico', code: 'MX' },
    { nl: 'Monaco', en: 'Monaco', code: 'MC' },
    { nl: 'Mongolië', en: 'Mongolia', code: 'MN' },
    { nl: 'Montenegro', en: 'Montenegro', code: 'ME' },
    { nl: 'Mozambique', en: 'Mozambique', code: 'MZ' },
    { nl: 'Myanmar', en: 'Myanmar', code: 'MM' },
    { nl: 'Namibië', en: 'Namibia', code: 'NA' },
    { nl: 'Nepal', en: 'Nepal', code: 'NP' },
    { nl: 'Nederland', en: 'Netherlands', code: 'NL' },
    { nl: 'Nieuw-Zeeland', en: 'New Zealand', code: 'NZ' },
    { nl: 'Nicaragua', en: 'Nicaragua', code: 'NI' },
    { nl: 'Nigeria', en: 'Nigeria', code: 'NG' },
    { nl: 'Noord-Korea', en: 'North Korea', code: 'KP' },
    { nl: 'Noord-Macedonië', en: 'North Macedonia', code: 'MK' },
    { nl: 'Noorwegen', en: 'Norway', code: 'NO' },
    { nl: 'Oekraïne', en: 'Ukraine', code: 'UA' },
    { nl: 'Oman', en: 'Oman', code: 'OM' },
    { nl: 'Oostenrijk', en: 'Austria', code: 'AT' },
    { nl: 'Pakistan', en: 'Pakistan', code: 'PK' },
    { nl: 'Panama', en: 'Panama', code: 'PA' },
    { nl: 'Paraguay', en: 'Paraguay', code: 'PY' },
    { nl: 'Peru', en: 'Peru', code: 'PE' },
    { nl: 'Polen', en: 'Poland', code: 'PL' },
    { nl: 'Portugal', en: 'Portugal', code: 'PT' },
    { nl: 'Qatar', en: 'Qatar', code: 'QA' },
    { nl: 'Roemenië', en: 'Romania', code: 'RO' },
    { nl: 'Rusland', en: 'Russia', code: 'RU' },
    { nl: 'Rwanda', en: 'Rwanda', code: 'RW' },
    { nl: 'Saoedi-Arabië', en: 'Saudi Arabia', code: 'SA' },
    { nl: 'Senegal', en: 'Senegal', code: 'SN' },
    { nl: 'Servië', en: 'Serbia', code: 'RS' },
    { nl: 'Singapore', en: 'Singapore', code: 'SG' },
    { nl: 'Slovenië', en: 'Slovenia', code: 'SI' },
    { nl: 'Slowakije', en: 'Slovakia', code: 'SK' },
    { nl: 'Spanje', en: 'Spain', code: 'ES' },
    { nl: 'Sri Lanka', en: 'Sri Lanka', code: 'LK' },
    { nl: 'Sudan', en: 'Sudan', code: 'SD' },
    { nl: 'Suriname', en: 'Suriname', code: 'SR' },
    { nl: 'Syrië', en: 'Syria', code: 'SY' },
    { nl: 'Taiwan', en: 'Taiwan', code: 'TW' },
    { nl: 'Tanzania', en: 'Tanzania', code: 'TZ' },
    { nl: 'Thailand', en: 'Thailand', code: 'TH' },
    { nl: 'Tunesië', en: 'Tunisia', code: 'TN' },
    { nl: 'Turkije', en: 'Turkey', code: 'TR' },
    { nl: 'Uganda', en: 'Uganda', code: 'UG' },
    { nl: 'Uruguay', en: 'Uruguay', code: 'UY' },
    { nl: 'Venezuela', en: 'Venezuela', code: 'VE' },
    { nl: 'Verenigd Koninkrijk', en: 'United Kingdom', code: 'GB' },
    { nl: 'Verenigde Arabische Emiraten', en: 'United Arab Emirates', code: 'AE' },
    { nl: 'Verenigde Staten', en: 'United States', code: 'US' },
    { nl: 'Vietnam', en: 'Vietnam', code: 'VN' },
    { nl: 'Zambia', en: 'Zambia', code: 'ZM' },
    { nl: 'Zimbabwe', en: 'Zimbabwe', code: 'ZW' },
    { nl: 'Zuid-Afrika', en: 'South Africa', code: 'ZA' },
    { nl: 'Zuid-Korea', en: 'South Korea', code: 'KR' },
    { nl: 'Zweden', en: 'Sweden', code: 'SE' },
    { nl: 'Zwitserland', en: 'Switzerland', code: 'CH' }
];

// Helper to get country name based on language
export function getCountryName(country, language = 'nl') {
    return country[language] || country.nl;
}

// Helper to search countries (searches both Dutch and English names)
export function searchCountries(query, language = 'nl') {
    if (!query) return COUNTRIES;

    const q = query.toLowerCase().trim();
    return COUNTRIES.filter(c =>
        c.nl.toLowerCase().includes(q) ||
        c.en.toLowerCase().includes(q) ||
        c.code.toLowerCase() === q
    );
}
